#!/bin/bash

FIRST=$(picl $1)
SECOND=$(picl $2)

if [ "$FIRST" = "$SECOND" ]
then
    >&2 echo -e "\033[92m($1, $2)"
    >&2 echo -en "\033[0m"
    exit 0
else
    >&2 echo -e "\033[31m($1, $2)"
    >&2 echo -e "$1: $FIRST"
    >&2 echo -e "$2: $SECOND"
    >&2 echo -en "\033[0m"
    exit 1
fi
